### ISSUE TITLE
Language work for mgmtconfig

### ISSUE THREAD

**Issue by purpleidea** [plasma-umass/Rehearsal#4]
Hey there,

I'm the primary author of a next generation config management tool called `mgmt`.
It's similar to puppet in some ways, but quite different in others. The project homepage is here:

https://github.com/purpleidea/mgmt/

At the bottom of the README.md file there are some links to blog posts and video recordings. The first blog post listed is the best place to start.

I figured I would mention the project here in case you are interested in participating, and helping to ensure that we build a correct, safe, tool! (These are certainly our goals, but with your help we'll surely converge on this goal sooner!)

Feel free to ping me here or on IRC. I'm purpleidea in #mgmtconfig on Freenode.

Cheers
James

**Comment by arjunguha** [comment]
Hi,

Sorry, we totally missed this open issue. I'd be happy to chat. The best way to reach me is email: arjun@cs.umass.edu.
